### ISSUE TITLE
heredocs don't fold correctly

### ISSUE THREAD

**Issue by Blahah** [atom/language-ruby#105]
unfolded code:

```ruby
def some_code
  <<-EOS
some text here
and some more
  EOS
end
```

expected after folding function block:

```ruby
def some_code [...]
end
```

observed after folding function block:

```ruby
def some_code [...]
some text here
and some more
  EOS
end
```

**Comment by 50Wliu** [comment]
Folding in Atom is currently based purely on indentation: see atom/atom#3442 for more details.
