### ISSUE TITLE
Fix embedded Ruby's scope

### ISSUE THREAD

**Issue by Arcanemagus** [atom/language-ruby#114]
It looks like [here](https://github.com/atom/language-ruby/blob/master/grammars/html%20(ruby%20-%20erb).cson#L74) and [here](https://github.com/atom/language-ruby/blob/master/grammars/html%20(ruby%20-%20erb).cson#L80) you are marking Ruby embedded in ERB files as the scope `source.ruby` instead of `source.embedded.ruby` as it should be. This is causing issues with [linter-ruby](https://github.com/AtomLinter/linter-ruby/issues/26) and [linter-rubocop](https://github.com/AtomLinter/linter-rubocop/issues/48) attempting to lint these files since they think they are pure Ruby.

**Comment by emilyaviva** [comment]
There is also an issue with linter-erb, which seems to be linting `.html.erb` files as if they were HTML.
<img width="450" alt="screen shot 2015-11-05 at 12 40 53 am" src="https://cloud.githubusercontent.com/assets/12450261/10963587/5d9f787e-8356-11e5-9ad5-f48392050bac.png">

**Comment by Arcanemagus** [comment]
`linter-erb` has not been updated to the current `linter` API as it seems to currently be abandoned, the errors you show are from `linter-ruby` and are a result of this language package incorrectly marking the embedded Ruby code as regular Ruby code (as stated over in https://github.com/AtomLinter/linter-ruby/issues/26#issuecomment-153991478).

**Comment by emilyaviva** [comment]
Makes sense.
