### ISSUE TITLE
Hash Pair snippet triggering when typing spaces

### ISSUE THREAD

**Issue by prismatica** [atom/language-ruby#127]
After typing `{myKey: ` and then pressing tab several times, the Hash Pair autocomplete suggestion pops up and will fire on the next tab, which then dumps `{myKey:key => "value",` into the editor. This is pretty frustrating. Ideally, once any other character has been typed after the colon, this suggestion will go away.

**Comment by 50Wliu** [comment]
Hi @prismatica, the trigger for the hash pair snippet has already been changed (to I believe `hp`).  It should be available in Atom 1.3.2 (or if not, 1.4.0 when it comes out).

**Comment by prismatica** [comment]
Woo, thanks!~
