### ISSUE TITLE
Multi-line regular expression using `//` is not highlighted correctly

### ISSUE THREAD

**Issue by andypike** [atom/language-ruby#144]
I have the following regex using `%r{}` which is highlighted correctly as follows:

![screen shot 2016-04-01 at 00 36 18](https://cloud.githubusercontent.com/assets/117697/14194074/478ecce0-f7a2-11e5-9569-9528a45e4fed.png)

I'm using the Rubocop linter and it suggested using `//` in this case so I made that change and the code works just fine, so this is valid Ruby but the syntax highlighting isn't the same:

![screen shot 2016-04-01 at 00 36 52](https://cloud.githubusercontent.com/assets/117697/14194095/78855ff8-f7a2-11e5-88c3-3217269ad596.png)

I've had a look through the package to try and fix it myself but I'm not 100% sure how the package works.  This is using Atom 1.6.0 and version 0.68.0 of this package. 

If there is any other information you need then please let me know. 

Thanks :heart:

**Comment by 50Wliu** [comment]
Thanks for the report!
