### ISSUE TITLE
Code completion (Snippet question)

### ISSUE THREAD

**Issue by IgorPolyakov** [atom/language-ruby#157]
Hello! I'm start to use atom, and I have a questions.

Snippets do not contain a complete list of [classes and methods][snip], according to [documentation][doc].
This is as it should be or it will expand in the future?

[snip]: <https://github.com/atom/language-ruby/blob/master/snippets/language-ruby.cson>
[doc]: <http://ruby-doc.org/core-2.3.0/index.html#classes>

**Comment by esdoppio** [comment]
The snippets feature is meant to help users improve their efficiency by letting them create shortcuts for text snippets that are frequently used, so, a snippet file is not intended to contain all the classes and methods. 😉 

Did you mean code suggestion and completion for Ruby?

**Comment by IgorPolyakov** [comment]
Sorry. Yes, I mean code completion)

**Comment by esdoppio** [comment]
Code completion in Atom for a language is backed by the *autocomplete-plus* package (pre-installed in Atom) with a provider for that language (which you might need to install yourself).

You could try searching in the *Install* panel under *Preferences* to see if the autocomplete provider you need is available 😄

**Comment by IgorPolyakov** [comment]
Ок))) It work) Thanks))
