### ISSUE TITLE
source keyword problem for Chef resources

### ISSUE THREAD

**Issue by fdevaux** [atom/language-ruby#164]
In d98bbd7170584ad7d30cd0c3a1ed1ba4e0d83707 `source` is added as a keyword. 

However `source` is also a property (which are normally not matched explicitly) in a number of Chef sources, such as the [template resource](https://docs.chef.io/resource_template.html).

Is there a way to match `source` only for Gemfiles?

**Comment by 50Wliu** [comment]
Fixed by #196.
