### ISSUE TITLE
public_class_method highlighted incorrectly

### ISSUE THREAD

**Issue by joesustaric** [atom/language-ruby#165]
<img width="440" alt="screen shot 2016-09-11 at 5 05 18 pm" src="https://cloud.githubusercontent.com/assets/199240/18415792/10d114c6-7842-11e6-9d5e-e69a182caecc.png">

mac 10.11.6
atom 1.10.2
language-ruby 0.68.5

**Comment by 50Wliu** [comment]
Cannot reproduce using language-ruby 0.70.1.  The fix should be out in Atom 1.12.0.
