### ISSUE TITLE
What is the preferred method for running the test suite?

### ISSUE THREAD

**Issue by AnthonyBobsin** [atom/language-ruby#166]
I would like to document this process within the Wiki, as I have tried a couple of different methods using Mocha and Jasmine but am unsure of what is preferred.

**Comment by 50Wliu** [comment]
@AnthonyBobsin `atom --test spec`.  Some other ways are documented [here](http://flight-manual.atom.io/hacking-atom/sections/writing-specs/#running-specs).

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by AnthonyBobsin** [comment]
@50Wliu Thank you for the quick response, I completely missed that in the Flight Manual.

Will remember to post similar questions to the Message Board in the future.
