### ISSUE TITLE
Float highlight a bit off

### ISSUE THREAD

**Issue by rmehner** [atom/language-ruby#168]
Since some releases ago (can't pinpoint the exact version), I'm seeing this highlightning issue:

![float-highlight-atom](https://cloud.githubusercontent.com/assets/82050/18874582/a3e6e8e4-84c2-11e6-937d-6e0ea9245a38.png)

Atom: 1.10.2
atom-language-ruby: 0.69.0

Thanks for all your work so far :)

**Comment by 50Wliu** [comment]
This has been fixed and should be making its way into the 1.11.0 release.

**Comment by rmehner** [comment]
FYI I'm still seeing this with Atom 1.11.1

**Comment by 50Wliu** [comment]
That was a typo - I actually meant 1.12.0 (and this time I mean it - you can verify by looking at 1.12's changelog).  Sorry!

**Comment by rmehner** [comment]
Haha, don't worry and thanks for your work on this :) I'll patiently wait for the release.
