### ISSUE TITLE
Autocomplete changes 'else' to 'elseif'

### ISSUE THREAD

**Issue by Albertc** [atom/language-ruby#172]
In Ruby Language, when type else (snippet else not elseif) appears elseif true

Image example:
typing:
![image](https://cloud.githubusercontent.com/assets/124529/19468187/49a6628e-9515-11e6-946a-2401d0b288df.png)

and then:
![image](https://cloud.githubusercontent.com/assets/124529/19468194/55666c0e-9515-11e6-97b9-8ac43a89ac1e.png)

**Comment by thomasjo** [comment]
Can you reproduce this in safe mode? Additionally, are you pressing `tab` or `enter`?

**Comment by Albertc** [comment]
It happens with enter and with Tab, is impossible to get "else" without, afterwards,  writing over "elseif true"
How to I reproduce in safe mode?

**Comment by thomasjo** [comment]
http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode

**Comment by 50Wliu** [comment]
language-ruby does not contain either an `else` snippet or an `elsee` snippet, which means that another package you have installed is causing this issue.

**Comment by Albertc** [comment]
In safe mode works correctly, so the problem now is to know which package causes this behaviour

**Comment by 50Wliu** [comment]
@Albertc Try [package-cop](https://atom.io/packages/package-cop).

**Comment by Albertc** [comment]
Still investigating, 
( I don't have package-cop )
What I see, is either of this two packages causes this issue ¿? If I enable one of those, "else" becomes "elseif"
![image](https://cloud.githubusercontent.com/assets/124529/19485724/37ae87ea-955c-11e6-9660-7a15063eb55d.png)

**Comment by 50Wliu** [comment]
Make sure you don't have an autocompletion package somewhere.  And try installing package-cop just for this; it'll probably help.
