### ISSUE TITLE
Feature: GraphQL Heredoc highlighting

### ISSUE THREAD

**Issue by bessey** [atom/language-ruby#173]
I'm not sure of the feasibility of this, but It would be nice if GraphQL was highlighted, as with SQL and other HEREDOC syntax. 

E.g.

![image](https://cloud.githubusercontent.com/assets/708200/19574140/d5411ede-96bd-11e6-9cfe-0957d40482cb.png)

highlighted with [language-graphql](https://atom.io/packages/language-graphql) to look like

![image](https://cloud.githubusercontent.com/assets/708200/19574159/eed23482-96bd-11e6-9a18-47149bc63935.png)

Happy to work on this if someone can point me in the right direction. I am (or would be) a first time contributor.

**Comment by 50Wliu** [comment]
Take a look at how [language-gfm](https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L296-L311) does it, then apply the same logic to Ruby's heredoc patterns.

**Comment by bessey** [comment]
Hmm, it seems i was wrong and this functionality already works with this syntax (note the quotes).
```ruby
<<~'GRAPHQL'
query portalQuery($id: ID!) {
  localProperty(id: $id) {
  }
}
'GRAPHQL'
```

Is this an Atom feature? I notice it works in Github Markdown too!

**Comment by bessey** [comment]
Bah, scratch that, its not highlighting like GraphQL, its highlighting like its Ruby.
