### ISSUE TITLE
Feature request: Auto conversion of single quote to double quote and vice-versa when selected and pressed the corresponding key

### ISSUE THREAD

**Issue by shivabhusal** [atom/language-ruby#201]
Hi, I would appreciate if you add this feature; it would make Ruby developer's life easier.

## Description
Consider the following line:
```
"Here a double quoted string; but I would like to make it single quoted"
'Here is a single quoted string, I would like to make it double quote to add interpolation'
```
- when I select the first line and press button `'` then, the double quote should change to single quotes.
- when I select the second line and press button `"` then, the single quote should change to double quotes.

Thanks!

**Comment by rsese** [comment]
Thanks for contributing!  I don't think this feature would go in this package since it's about syntax highlighting and snippets for Ruby but there's a package for quote toggling that you can use:

https://github.com/atom/toggle-quotes
