### ISSUE TITLE
Multiline YARD highlighting for tag–comment styles

### ISSUE THREAD

**Issue by cbothner** [atom/language-ruby#228]
### Description

YARD supports multiline comments for tags [as long as the following lines are indented](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#Multi-line_Tags) but atom-language-ruby does not extend syntax highlighting beyond the line. Namely, I expect the text on the second line to be green.

<img width="631" alt="screen shot 2018-01-23 at 10 23 45" src="https://user-images.githubusercontent.com/4642599/35283953-8d83eda4-0027-11e8-9681-784063e4adb4.png">

I am interested in implementing this but am looking for some guidance.

I tried naively to extend the [`yard_name_types` pattern](https://github.com/atom/language-ruby/blob/3c78983017c34cfc234f73ed48eb6661f27358a4/grammars/ruby.cson#L2319) to match multiple lines, [like this](https://regexr.com/3jl3s). But as y’all more experienced syntax highlighters already know, you can’t use multiline patterns.

I think the [begin and end keys](https://manual.macromates.com/en/language_grammars#rule_keys) are promising, but while I can figure that maybe the begin pattern would be something like `# @(attr|etc.)`, there’s no natural end key. How do you match “the lack of a comment line with two more spaces of indentation than this one” precisely enough?

Any ideas? Am I totally off base here? Is there a better dev workflow for language grammars than painstakingly restarting Atom after every change?

**Comment by 50Wliu** [comment]
> How do you match “the lack of a comment line with two more spaces of indentation than this one”

Oh boy, do I have [experience](https://github.com/atom/language-yaml/blob/master/grammars/yaml.cson) with this.  I believe you essentially want something like `^(?!\\s*#\\1\\s{2,})` as your end pattern where `\\1` refers to the capture group in `^\\s*#(\\s*)` which you'll stick at the beginning of your begin pattern.
