### ISSUE TITLE
Inherited class names are highlighted the same as other class and module names

### ISSUE THREAD

**Issue by npezza93** [atom/language-ruby#242]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Inherited class names used to have an extra class that distinguished them as an inherited class. They no longer do with TreeSitter. 
Using the example: 
```ruby
class OrderItem < ApplicationRecord
end
```

With TreeSitter off:
The less than and inherited class name are grouped together with the `.syntax--entity.syntax--other.syntax--inherited-class` classes. 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/5059927/47459725-e0c1a780-d7aa-11e8-8596-158af52a18e5.png">

With TreeSitter on:
The inherited class is treated like a normal class name and has the following classes: `syntax--entity syntax--name syntax--type syntax--class`
<img width="448" alt="image" src="https://user-images.githubusercontent.com/5059927/47459716-da333000-d7aa-11e8-834f-39b175ee35c3.png">

I can see why this could be intentional as it is just a class name but I enjoyed being able to style inherited classes differently. 

### Steps to Reproduce

1. Type the above example and toggle TreeSitter using the one dark theme

**Expected behavior:** The inherited class name to have an extra class that distinguishes it as an inherited class name.
**Actual behavior:** It is treated like any other class or module name.

**Reproduces how often:** 100%

### Versions

1.34.0-nightly2

**Comment by rsese** [comment]
And thanks for this one too :v:  Reproduced as described with 1.34.0-nightly0 on macOS 10.12.6.
