### ISSUE TITLE
Block parameters no longer able to be styled

### ISSUE THREAD

**Issue by npezza93** [atom/language-ruby#243]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Block parameters and surrounding pipes are grouped as one node and cannot be separately styled. 

With TreeSitter on:

```html
<div class="line cursor-line" style="" data-screen-row="47">
  <span class="">
    <span class="syntax--entity syntax--name syntax--function">imablock</span> 
    <span class="syntax--keyword syntax--control">do</span> 
    |param1, param2|
  </span>
</div>
```

<img width="362" alt="image" src="https://user-images.githubusercontent.com/5059927/47461034-d1902900-d7ad-11e8-8034-c5ac9f1b45f5.png">

With TreeSitter off:
```html
<div class="line cursor-line" style="" data-screen-row="47">
  <span class="">
    <span class="syntax--source syntax--ruby">
      imablock 
      <span class="syntax--keyword syntax--control syntax--start-block syntax--ruby">do</span> 
      <span class="syntax--punctuation syntax--separator syntax--variable syntax--ruby">|</span>
      <span class="syntax--variable syntax--other syntax--block syntax--ruby">param1</span>
      <span class="syntax--punctuation syntax--separator syntax--object syntax--ruby">,</span> 
      <span class="syntax--variable syntax--other syntax--block syntax--ruby">param2</span>
      <span class="syntax--punctuation syntax--separator syntax--variable syntax--ruby">|</span>
    </span>
  </span>
</div>
```

<img width="340" alt="image" src="https://user-images.githubusercontent.com/5059927/47461102-04d2b800-d7ae-11e8-9f1e-6f8822bd5042.png">

Now with TreeSitter on I can how this styling might be the default because it is _almost_ the exact same as a normal method definition:
```html 
<div class="line cursor-line" style="" data-screen-row="44">
  <span class="">
    <span class="syntax--keyword syntax--control">def</span> 
    <span class="syntax--entity syntax--name syntax--function">imablock</span>
    <span class="syntax--punctuation syntax--definition syntax--parameters">(</span>
    param1, param2
    <span class="syntax--punctuation syntax--definition syntax--parameters">)</span>
  </span>
</div>
```
<img width="345" alt="image" src="https://user-images.githubusercontent.com/5059927/47461172-2b90ee80-d7ae-11e8-838a-a84b9d6941a8.png">

But in a method definition the parenthesis are wrapped in their own element. So
1. Could we get the ability to style block parameters?
2. If one is not possible or is working as desired, could we wrap the pipes with their own classes like what's on method definitions?

Thanks!

### Steps to Reproduce

1. Create a block like shown above and toggle TreeSitter using the One Dark syntax theme.

**Expected behavior:** To be able to style block parameters
**Actual behavior:** Can no longer styling block parameters
**Reproduces how often:** 100%

### Versions
1.34.0-nightly2

**Comment by rsese** [comment]
Thanks for these report @npezza93 - just noting I can reproduce what you describe with 1.34.0-nightly0 on macOS 10.12.6, we'll ask the team to take a look.
