### ISSUE TITLE
Incorrect highlighting for numbers with decimal point, e, B and D

### ISSUE THREAD

**Issue by husseinkhaleel** [atom/language-ruby#251]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With tree-sitter enabled, numbers with a decimal point (1.0) and e (e.g. 1e3) are not highlighted. Also, numbers defined with capital B (binary) and capital D (decimal) are not highlighted correctly, and possibly parsed under a different category. Small letter b and d are highlighted correctly though.
These were the numerical representations that were tested, others could also have the same problem.
When tree-sitter is disabled, the highlighting is correct/as expected.
This is shown in the images below.

Tree-sitter enabled (by default):
<img width="231" alt="screen shot 2018-11-12 at 4 25 38 pm" src="https://user-images.githubusercontent.com/44983951/48377719-84142700-e69c-11e8-928d-21df4c157cf2.png">

Tree-sitter disabled:
<img width="236" alt="screen shot 2018-11-12 at 4 25 10 pm" src="https://user-images.githubusercontent.com/44983951/48377770-ac9c2100-e69c-11e8-972b-862a875d0971.png">

### Steps to Reproduce

1. Create a new .rb file.
2. Enable tree-sitter (Preferences->Core) (should be enabled by default).
3. Declare variables and assign values having decimal point, e, B and D. One can copy-paste the following:
a = 10
b = 1.0
c = 1e3
d1 = 0xA; d2 = 0XA
e1 = 0o7; e2 = 0O7
f1 = 0b01; f2 = 0B01
g1 = 0d10; g2 = 0D10
4. Notice the missing/incorrect numerical highlighting.
5. Disable tree-sitter (Preferences->Core)
6. Notice the correct numerical highlighting.

**Expected behavior:** All numerical values should be highlighted correctly.

**Actual behavior:**

- Numerical values with decimal point and e are not highlighted.
- Numerical values with B and D are not highlighted correctly.

**Reproduces how often:** 100%

### Versions

$ atom --version
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.10
git 2.18.0

MacOS Mojave
Version 10.14.1 (18B75)

### Additional Information

N/A

**Comment by Ben3eeE** [comment]
@maxbrunsfeld These seem to parse as syntax error:

![image](https://user-images.githubusercontent.com/1058982/48396439-c2502b80-e71a-11e8-9acd-a687c9fd22fb.png)

**Comment by husseinkhaleel** [comment]
They should be correct syntax. I use ruby 2.4.2, and these lines execute correctly on my PC.
Here is ruby language documentation:
https://docs.ruby-lang.org/en/2.0.0/syntax/literals_rdoc.html
If one looks into the "Numbers" section, it says:
"The alphabetic component of the number is not case-sensitive"

**Comment by husseinkhaleel** [comment]
In the ruby.cson file on this repository, the identification 'pattern' for numeric checks for both upper- and lower-cases, as shown in the image below.
![screen shot 2018-11-13 at 9 34 26 am](https://user-images.githubusercontent.com/44983951/48420210-e6663980-e727-11e8-9233-cce2a69f0332.png)
