### ISSUE TITLE
Strange delay when syntax highlighting

### ISSUE THREAD

**Issue by mcandre** [atom/language-ruby#253]
I have to keep inserting dummy lines and then deleting them in order to get language-ruby to update the syntax highlighting while I edit my Ruby code. This happens, for example, with Rakefiles.

**Comment by rsese** [comment]
Thanks @mcandre - can you confirm if you're still having the same trouble in the releases from yesterday (1.33.0 and 1.34.0-beta0)?  There were a number of Tree-sitter fixes in these releases.

If you can reproduce, please update the issue body with the issue template details (exact steps to reproduce would be super helpful) so the team can take a look.
