### ISSUE TITLE
Inconsistency on percent string symbol syntax using Tree-sitter

### ISSUE THREAD

**Issue by foreverqihe** [atom/language-ruby#255]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The symbol syntax doesn't get rendered correctly:
using Tree Sitter
![image](https://user-images.githubusercontent.com/2378002/48941674-a0ec0c80-ef70-11e8-9e63-259de85132fe.png)

NOT using Tree Sitter
![image](https://user-images.githubusercontent.com/2378002/48941699-bcefae00-ef70-11e8-8ebb-b54a4c7270de.png)

*Edit by @rsese with scope screenshots:*

it does seem like the tokens should be scoped as symbols?

![percent-string-symbols](https://github-slack.s3.amazonaws.com/monosnap/test.rb__worktest-tree-sitter_2018-11-29_19-44-36.png)

![symbol](https://github-slack.s3.amazonaws.com/monosnap/test.rb__worktest-tree-sitter_2018-11-29_19-47-25.png)

### Steps to Reproduce

1.  Open Atom
2. Open a Ruby file
3. write code show as the snapshot

**Expected behavior:** [The color should be consistent as the syntax  is an alternative syntax for symbol in Ruby so it should be the same color as other symbols]

**Actual behavior:** [using Tree Sitter, when we write the symbol with the %i syntax, the color changed to brown]

**Reproduces how often:** [Always]

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows 7

**Comment by rsese** [comment]
Thanks for the report - it does seem like the tokens should be scoped as symbols?

![percent-string-symbols](https://github-slack.s3.amazonaws.com/monosnap/test.rb__worktest-tree-sitter_2018-11-29_19-44-36.png)

![symbol](https://github-slack.s3.amazonaws.com/monosnap/test.rb__worktest-tree-sitter_2018-11-29_19-47-25.png)

Not 100% sure but we'll ask the team to take a look.

**Comment by jasonrudolph** [comment]
This is resolved as of https://github.com/atom/language-ruby/pull/271, so I'm gonna close this out. You can see the changes below. 😅

### Atom 1.40.0 (current stable release)

<img width="742" alt="Screen Shot 2019-08-16 at 9 59 00 AM" src="https://user-images.githubusercontent.com/2988/63173279-8a5d7800-c00d-11e9-96b1-dab0fab4e909.png">

### Atom 1.42.0-nightly2 (current nightly release)

<img width="742" alt="Screen Shot 2019-08-16 at 10 03 50 AM" src="https://user-images.githubusercontent.com/2988/63173280-8a5d7800-c00d-11e9-8cde-079fc5ed5139.png">
