### ISSUE TITLE
Inconsistent highlighting of constants

### ISSUE THREAD

**Issue by mcandre** [atom/language-ruby#265]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

The syntax highlighter gets confused and highlights source code content incorrectly.

### Steps to Reproduce

Write a Rakefile like this:

```ruby
VERSION = '0.0.1'
PROVIDER = 'virtualbox'
BOX_NAMESPACE = 'mcandre'

BOX_BASENAME = 'mucus'
BOX_BASENAME_MIPS64EL = "#{BOX_BASENAME}-mips64el"
BOX_BASENAME_MIPSEL = "#{BOX_BASENAME}-mipsel"
BOX_BASENAME_S390X = "#{BOX_BASENAME}-s390x"

BOX_MIPS64EL = "#{BOX_BASENAME_MIPS64EL}.box"
BOX_MIPSEL = "#{BOX_BASENAME_MIPSEL}.box"
BOX_S390X = "#{BOX_BASENAME_S390X}.box"
```

**Expected behavior:**

language-ruby highlights all bindings with one color, all raw string content with another color.

**Actual behavior:**

language-ruby highlights bindings inconsistently, and also highlights raw string content inconsistently.

*Edit by @rsese: scopes screenshot with 1.40.0-nightly23 on macOS 10.14.*

![ruby-scopes](https://user-images.githubusercontent.com/734194/61313341-dffcf580-a7bf-11e9-9bf8-a36d6c6a43cc.png)

**Reproduces how often:**

Always.

### Versions

Atom v1.38.2

```console
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.16
git 2.20.1
```

Host: Ubuntu 19.04 Disco Dingo amd64

**Comment by rsese** [comment]
Thanks for the report and the example code :bow:  Reproduced with 1.40.0-nightly23 on macOS 10.14.

![ruby-scopes](https://user-images.githubusercontent.com/734194/61313341-dffcf580-a7bf-11e9-9bf8-a36d6c6a43cc.png)
