### ISSUE TITLE
Tree Sitter doesn't highlight public/private/protected

### ISSUE THREAD

**Issue by swrobel** [atom/language-ruby#268]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

public/private/protected keywords should be highlighted, but they are not

### Steps to Reproduce

Open a Ruby source file with the following code:

```ruby
class Test
  public
  private
  protected
end
```
(note that github highlights correctly)

**Expected behavior:**

With tree-sitter parsers disabled:
<img width="113" alt="Screen Shot 2019-07-29 at 6 31 06 PM" src="https://user-images.githubusercontent.com/157270/62093671-165e5a00-b22f-11e9-935d-a0f8fd98ad54.png">

**Actual behavior:**

With tree-sitter parsers enabled:
<img width="103" alt="Screen Shot 2019-07-29 at 6 31 24 PM" src="https://user-images.githubusercontent.com/157270/62093684-1e1dfe80-b22f-11e9-9d1d-5fe57e180156.png">

**Reproduces how often:**

100%

### Versions

Atom    : 1.40.0-beta1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0-beta1
python 2.7.10
git 2.22.0

macOS 10.14.6

**Comment by rsese** [comment]
Thanks for the report!  Reproduced on 1.39.1 on macOS 10.14.
