### ISSUE TITLE
Symbol literals have incorrect class

### ISSUE THREAD

**Issue by npezza93** [atom/language-ruby#270]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Symbol literals have the `syntax--constant syntax--other` classes attached to them and are thus highlighted as constants which is incorrect. They should be highlighted like symbols and have `syntax--constant syntax--other syntax--symbol` classes.

### Steps to Reproduce

1. Type the following in a ruby file:
```ruby
%i(thing) 
%I(thing #{thing})
:thing 
```
2. Notice all instances of `thing` on the first two lines are a different color than the last `thing` instance.

**Expected behavior:**

All instances of `thing` should be the same color.

**Actual behavior:**

They are a different color.

**Reproduces how often:**

100%

### Versions

macOS Mojave
atom 1.42.0-nightly0

**Comment by rsese** [comment]
Thanks @npezza93 - reproduced on macOS 10.14.6 with 1.42.0-nightly1:

![ruby-constants](https://user-images.githubusercontent.com/734194/62916332-93c0b900-bd5d-11e9-8b96-0fcda9d889e5.png)

**Comment by jasonrudolph** [comment]
I've opened https://github.com/atom/language-ruby/pull/271 to fix this issue.

**Comment by jasonrudolph** [comment]
This is now fixed on Atom's master branch, and it will be available in on the [Atom Nightly channel](https://atom.io/nightly) tomorrow.

Thanks for the bug report, @npezza93. :bow: Also, I see on your profile that you're in Durham. :wave: Hello from another Atom+Ruby fan in Durham! Small world. 😄

**Comment by npezza93** [comment]
Awesome, thanks @jasonrudolph! Nice to meet another fellow Durham+Atom+Rubyist!
