### ISSUE TITLE
Final `end` does not get highlighted after a block with a rescue inside a method

### ISSUE THREAD

**Issue by calebmeyer** [atom/language-ruby#274]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Ruby 2.6 added the ability to do a rescue without a corresponding begin inside a block. That means code like
```ruby
arr.each do |thing|
  begin
    try(thing)
  rescue error
    handle_it
  end
end
```
can be rewritten a little shorter (omitting the begin, and fixing the indentation):
```ruby
arr.each do |thing|
  try(thing)
rescue error
  handle_it
end
```

### Steps to Reproduce

1. Put a block like the above into a method

**Expected behavior:**
All `end` tags are syntax highlighted

**Actual behavior:**
The method's end tag loses highlighting:
![image](https://user-images.githubusercontent.com/3342777/63360444-04566f80-c334-11e9-84f7-8ef183150cca.png)

**Reproduces how often:**
100% of the time

### Versions
```
atom --version

Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm --version
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.7.2
git 2.16.2.windows.1
visual studio

OS: Windows 10 Enterprise (1809)
```

### Additional Information
None at this time

**Comment by alxtz** [comment]
Hi @calebmeyer , I think this problem is related to https://github.com/tree-sitter/tree-sitter-ruby

since the tree sitter parser I'm testing doesn't recognize the syntax in the first place

![image](https://user-images.githubusercontent.com/16031425/66177490-39c0dd80-e694-11e9-9b10-e09fe536b0c4.png)

![image](https://user-images.githubusercontent.com/16031425/66177573-8a383b00-e694-11e9-92e7-a6b1d6c684d8.png)

**Comment by calebmeyer** [comment]
Closing this in favor of https://github.com/tree-sitter/tree-sitter-ruby/issues/112 then
