### ISSUE TITLE
VS code support

### ISSUE THREAD

**Issue by JustinzGit** [atom/language-ruby#284]
## Summary

This language package in combination with tree-sitter provides really nice syntax highlighting that I've grown to love and do not wish to part from. After moving to VS code I struggle to obtain this type of highlighting even with the tree-sitter extension included. Is it possible that we could convert this package to an extension to enable use in VS code?

## Motivation

Transfer from Atom to VS code and keep syntax highlighting the same

## Describe alternatives you've considered

Customizing colors via text mate rules

**Comment by Arcanemagus** [comment]
You'll need to ask the VS Code team about this, we have nothing to do with it.
