### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by SampsonCrowley** [atom/language-ruby#287]
Is this package abandoned? There haven't been any updates for 7+ months, pull requests that have been open since 2018, and none of the issues that I've looked at have received any response from maintainers

**Comment by Rockster160** [comment]
Hope not. I imagine this is a well used package. Been having a lot of syntax highlighting issues lately. 🙁

**Comment by SampsonCrowley** [comment]
@Rockster160 yet still can't even get a "No we're just busy" from maintainers

**Comment by laimison** [comment]
Any updates that you are aware?

Anyone knows alternatives to `language-ruby` as the colours in Ruby syntax are broken? So Ruby can't be used in Atom.

Almost all my code is in grey, because of `.gsub(%r{#{diff_string}}, '')` at least.

I had to switch my favourite Atom editor to Virtual Studio Code until it's solved or I will get comfortable with VS so Atom will not be needed.

**Comment by laimison** [comment]
As I see, last merge was on 31 Oct 2019 and new ones are not just merged. So sadly it was left in unusable state 1 year and 3 months ago.

**Comment by laimison** [comment]
That is a how to migrate to `language-ruby-on-rails`. So at least no issues with colours.

1) Install `language-ruby-on-rails` package in Atom

2) Change syntax checker for `.rb` files from `language-ruby` to `language-ruby-on-rails`:

```
"*":
  core:
    customFileTypes:
      "source.ruby.rails": [
        "rb"
      ]
```

3) Restart Atom

**Comment by SampsonCrowley** [comment]
Language ruby-on-rails is a worse package in my opinion a lot of the time, the chosen colors are terrible, and another specialized package doesn't change that this package was just abandoned with no reason or warning

**Comment by darangi** [comment]
Hi @SampsonCrowley, this package has not been abandoned, we have a lot on our backlog.

Thanks for bringing this to our notice, We will  look at the existing PRs and Issues and review them
