### ISSUE TITLE
No release since Nov 2019

### ISSUE THREAD

**Issue by HarlemSquirrel** [atom/language-ruby#293]
There have been several updates.

https://github.com/atom/language-ruby/compare/v0.72.23...master

Please create a new release.

**Comment by brunnopleffken** [comment]
Who's the maintainer? Maybe some of these changes should resolve #261 (basically the greatest issue of this package).

**Comment by pyromaniac** [comment]
Please please please 🙇

**Comment by SampsonCrowley** [comment]
RELEASE A NEW VERSION ALREADY OMG

sorry but this is getting freaking ridiculous it's been more than 2 years with multiple PRs justbeing straight up ignored

**Comment by collimarco** [comment]
There is a new tag in the releases (2 days ago), however I don't get any update when I try to update the packages from Atom.

**Comment by collimarco** [comment]
Despite the new release, I still have v0.72... and no updates available. 

Why? How can I upgrade to v0.73?

**Comment by darangi** [comment]
Hi @collimarco, `v0.73` will be available on the next [nightly](https://atom.io/nightly) release which happens everyday. Also, you can get `v0.73` manually by cloning the `language-ruby` repo, in the directory run `apm install` once it is successful, you should do `apm link`. Reload atom and you have the latest changes from `language-ruby`
