### ISSUE TITLE
No recognition of Module::Class.method syntax for highlighing.

### ISSUE THREAD

**Issue by ryanmt** [atom/language-ruby#50]
I'm seeing problems with the syntax highlighting recognition of the Module and Class construct, and the Class.method construct.

![screen shot 2014-08-26 at 8 12 49 am](https://cloud.githubusercontent.com/assets/299377/4045580/34d4f266-2d2b-11e4-947e-86be429c1a2c.png)

It recognizes `Class` and sort of recognizes `Module::Class` but definitely misses `Class.method`
![screen shot 2014-08-26 at 8 14 50 am](https://cloud.githubusercontent.com/assets/299377/4045600/5ed10262-2d2b-11e4-8ea9-e800b6ed9d4f.png)

**Comment by elifoster** [comment]
Shouldn't this be closed as it's a solarized dark issue rather than a language-ruby issue?
