### ISSUE TITLE
Atom doesn't recognize keyword: val as different than a normal param.

### ISSUE THREAD

**Issue by envygeeks** [atom/language-ruby#61]
Can we please get highlighting support for:

```ruby
def function(keyword: var)
  "win"
end
```

So that we can highlight the keyword different than a normal param.

**Comment by jeremyf** [comment]
@kevinsawicki I also think that adding "keyword" to the correspond classes would be great.

**Comment by andrefreitas** [comment]
Any update on this?

**Comment by mamenama** [comment]
Just added cd706678154e874c42cb119aab8b24932b1400fa to PR #113 which gives the symbols in the hash the class constant.other.symbol.hashkey.ruby consistent with other symbol hashkeys. Is this along the lines of what you were looking for? (We can tag it something else, I suppose, but I was trying to be consistent with other symbols - let me know)

**Comment by envygeeks** [comment]
Thanks @mamenama!   I think I would also add function.paramater to it as well!

**Comment by mamenama** [comment]
OK - added them in 41fb848beef0852d07d5aa5e91edfbb62bb13695 which is now also part of PR #113 - take a look and let me know if that's what you were looking for.

**Comment by 50Wliu** [comment]
Fixed by #113.
