### ISSUE TITLE
Wrong highlighting

### ISSUE THREAD

**Issue by matiasgarciaisaia** [atom/language-ruby#62]
Both with and without soft wrapping enabled, `atom --safe` fails to highlight [this file](https://github.com/instedd/resourcemap/blob/52ba6a0a368120245cfc0be4a61b856296567744/spec/controllers/sites_controller_spec.rb).

![screen shot 2014-10-06 at 4 47 52 pm](https://cloud.githubusercontent.com/assets/5470539/4532314/b6f0abd8-4d91-11e4-800d-6809d2c94bc8.png)

Running atom 0.135.0 with Language Ruby 0.38.0 on MacOS X 10.9.5

**Comment by kevinsawicki** [comment]
Can you provide the raw contents of the file that failed to highlight? This will be very hard to reproduce and fix without it.

**Comment by matiasgarciaisaia** [comment]
@kevinsawicki: I've linked it at the original report - I knew I would forget about this :)

https://github.com/instedd/resourcemap/blob/52ba6a0a368120245cfc0be4a61b856296567744/spec/controllers/sites_controller_spec.rb

10 months and 80 releases later, it's nice to say that this is less of an issue now - ie, the highlighting works _way_ better -, but it's still failing with the last arrows of line 14:

![](https://cloud.githubusercontent.com/assets/5470539/9126507/29dfcf5c-3c84-11e5-8e4e-6fc040cdb0a4.png)

**Comment by kevinsawicki** [comment]
Okay, thanks for the link to the file, I think the remaining issue is https://github.com/atom/atom/issues/1667 so I'm going to close this out here. You may want to subscribe to that issue to know when this is finally resolved.
