### ISSUE TITLE
`def meth *args` does not get highlighted like `def method(*args)`

### ISSUE THREAD

**Issue by envygeeks** [atom/language-ruby#69]
`def meth *args` ends up leading to the `*` being marked what `(` is usually highlighted as (`punctuation.definition` along with `variable.ruby`) instead of as a storage modifier.

**Comment by mamenama** [comment]
Edited the grammar in commit 9e0c35094650e59c088428e82c927d3aa4106ec7 so that the two behave the same.

**Comment by lee-dohm** [comment]
It looks like the commit @mamenama is referring to is part of #113 (for more context).

**Comment by 50Wliu** [comment]
Fixed by #113.
