### ISSUE TITLE
attr_reader shortcut is incorrectly taking precedence over existing snippet being used

### ISSUE THREAD

**Issue by jnunemaker** [atom/language-ruby#70]
1. Type "def" and hit tab to start using the define a method snippet.
2. Type method name that ends with "r" like "test_subscriptions_with_sort_order".
3. Hit tab.

Result: 

```
def test_subscriptions_with_sort_ordeattr_reader :attr_names

end
```

Expected:

```
def test_subscriptions_with_sort_order
  <cursor here>
end
```

This just recently started happening.

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/snippets/pull/99
