### ISSUE TITLE
Parentheses in Default Parameter Mess Up Highlighting

### ISSUE THREAD

**Issue by pducks32** [atom/language-ruby#78]
Having a default parameter use a `)` messes up syntax highlighting. I tried to fix the issue myself but just don't have enough experience with the code to find out how to deal with it. Interestingly enough it doesn't happen if the `)` is in a string and it doesn't happen with other recursive tokens like `%(te(s)t)`

![screen shot 2014-12-26 at 9 26 21 pm](https://cloud.githubusercontent.com/assets/6308109/5560323/4000dc4c-8d46-11e4-8336-dc2571431de7.png)

**Comment by mamenama** [comment]
Added a fix in commit 34813e62e45dd2bfaa3088a55416efc364d5a522 of Pull Request #113 - now it uses the paren at the end of the line as the delimiter rather than the first closing paren it sees.

**Comment by 50Wliu** [comment]
Fixed by #113.
