### ISSUE TITLE
pound should assume user is interpolating if used within double quotes

### ISSUE THREAD

**Issue by arelenglish** [atom/language-ruby#8]
When a user highlights something in a double quote string and presses pound it should assume the use wants to interpolate. Right now it replaces the highlighted text with a pound symbol. 

Pressing pound within a double quoted string should also assume the user intends to interpolate. 

e.g. 

``` ruby
"#{}"
" Good morning #{user} It is good to see you."
```

**Comment by JacobHilbert** [comment]
there is no way to turn this off? I do not see anything in the settings.
