### ISSUE TITLE
Add automatic `end`

### ISSUE THREAD

**Issue by npassaro** [atom/language-ruby#85]
It would be interesting to add the ability to automatically add `end` in the next line when writing new:
* classes
* modules
* methods
* blocks
* conditional statements
* etc.

Thanks.

**Comment by philipgiuliani** [comment]
Some of this are already possible.
Write for example `def` and press TAB then.

Seems that `class` and `module` snippets are missing.

**Comment by envygeeks** [comment]
Edit > Snippets:

```cson
'.source.ruby':
  'module':
    'prefix': 'module'
    'body': 'module $1\n  $2\nend'

  'pry':
    'prefix': 'pry'
    'body': 'require "pry"; binding.pry$1'

  'class':
    'prefix': 'class'
    'body': 'class $1\n  $2\nend'
```

**Comment by BitOfUniverse** [comment]
You can actually use 'cla'/'mod' + tab, see full list of snippets: 
https://github.com/atom/language-ruby/blob/master/snippets/language-ruby.cson

**Comment by envygeeks** [comment]
This ticket was made well before any of that.
