### ISSUE TITLE
regular expression in hash table

### ISSUE THREAD

**Issue by ztq56** [atom/language-ruby#86]
In a hash table like `{a: /#{x}/i}` or `{:a => /#{x}/i}` the regex is not rederred as expected

**Comment by 50Wliu** [comment]
Can we please see a picture with how it's supposed to be highlighted (in a different editor like Sublime/Textmate) vs how it's currently highlighted?

**Comment by ztq56** [comment]
![snapshot7](https://cloud.githubusercontent.com/assets/730813/6775841/f6189064-d171-11e4-9423-a9def4a53d10.png)
![snapshot8](https://cloud.githubusercontent.com/assets/730813/6775888/6f5504bc-d172-11e4-8571-c24e613b6080.png)
like this, atom: 0.186.0, language-ruby: 0.49.0,
the syntax highlight works fine in Sublime and vim

**Comment by kevinsawicki** [comment]
Thanks for reporting this, it will be fixed in the next Atom release, 0.189
