### ISSUE TITLE
ERB Syntax highlighting does not work correctly. Highlight only some lines. Others no colors at all

### ISSUE THREAD

**Issue by THPubs** [atom/language-ruby#95]
As seen in the following image, some lines in my erb file have syntax highlighting but some does not! Why is that?
![atom-erb-issue](https://cloud.githubusercontent.com/assets/1212023/7666052/8ed18e38-fbf1-11e4-9d31-9dad7a1612c7.png)

**Comment by vortizhe** [comment]
Same problem here, is there any way to disable erb grammar from this package and use RoR(html) instead?

**Comment by kevinsawicki** [comment]
@benogle do you think this might be due to the `language-html` changes?

@THPubs if you put a space between `<li>` and `<%=` does it highlight then?

**Comment by benogle** [comment]
> @benogle do you think this might be due to the language-html changes?

probably

**Comment by taylon** [comment]
I strongly believe it's due to recent changes to language-html, I have tested some grammars that include text.html.basic and they are all broken, all with very similar issues...

https://github.com/atom/language-html/issues/62

**Comment by THPubs** [comment]
@kevinsawicki Yep :-) If we add a space it works. But better if you can make it both ways right?

**Comment by benogle** [comment]
This should be fixed in the most recent version of atom. Please comment if it is still broken for you.

**Comment by Alphabetus** [comment]
it is still broken... or broken again.
any ERB will randomly cause highlight to vanish.

**Comment by Aerijo** [comment]
@Alphabetus The syntax highlighting has changed dramatically since this issue was closed, please look for an open one or make a new one with the template filled out.

**Comment by JoeQuattrone** [comment]
Its still broken for me
