### ISSUE TITLE
`require` method call improperly highlighted as special `require` function call

### ISSUE THREAD

**Issue by nn2242** [atom/language-ruby#99]
`require` is a super special function in Ruby, but it isn't special if it's a method call: 

![screen shot 2015-05-21 at 2 19 49 pm](https://cloud.githubusercontent.com/assets/2596124/7755745/849ca23c-ffc4-11e4-84cb-98a5908726b6.png)

Should only highlight if not a class/instance method call?

**Comment by 50Wliu** [comment]
Fixed by #100.
